name: Publish package to GHCR

on: push

env:
  IMAGE_NAME: nogcorp

jobs:

  ghr_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Sign in to GHCR
        run: echo "${{ secrets.MY_TOKEN}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Get k8s credentials
        run: doctl kubernetes cluster kubeconfig save caitkube
      - name: Deploy nogcorp
        run: kubectl -n nogcorp rollout restart deployment nogcorp
